version: '3.8'

services:
  mm-exporter:
    build:
      context: ../../
      dockerfile: exporter/examples/Dockerfile
    container_name: mm-exporter
    image: mm-exporter:latest
    restart: unless-stopped

    # Network configuration
    network_mode: host

    # D-Bus access (required for ModemManager communication)
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      - /sys:/sys:ro

    # Privileged mode (required for D-Bus system bus access)
    privileged: true

    # Environment variables
    environment:
      - TZ=UTC

    # Command line arguments (customize as needed)
    command:
      - "-listen-address=:9539"
      - "-metrics-path=/metrics"
      - "-signal-rate=5s"

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9539/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Labels
    labels:
      - "com.example.description=ModemManager Prometheus Exporter"
      - "com.example.version=1.0.0"

  # Optional: Prometheus server for testing
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - mm-exporter

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
